service: full-lambda-function-dynamodbNext

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  tracing: 
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource: '*'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-tracing
package:
  include: src/**/*
  exclude:
    - node_modules/**/*

  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    platform: node
    concurrency: 10

functions:
  createUser:
    handler: src/functions/handlers.createUser
    tracing: true
    events:
      - httpApi:
          path: /user
          method: post
  getUsersList:
    handler: src/functions/handlers.getUsersList
    tracing: true
    events:
      - httpApi:
          path: /UsersListNext
          method: get
  getUserById:
    handler: src/functions/handlers.getUserById
    tracing: true
    events:
      - httpApi:
          path: /user/{id}
          method: get

resources:
  Resources:
    UsersListTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: UsersListNext
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        
