service: full-lambda-function-dynamodbNext

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  tracing: 
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource: '*'

custom:
  alerts:
    stages: # Optionally - select which stages to deploy alarms to
      - dev     

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-aws-alerts    

package:
  include: src/**/*
  exclude:
    - node_modules/**/*

functions:
  createUser:
    handler: src/functions/handlers.createUser
    tracing: true
    events:
      - httpApi:
          path: /user
          method: post
  getUsersList:
    handler: src/functions/handlers.getUsersList
    tracing: true
    events:
      - httpApi:
          path: /UsersListNext
          method: get
  getUserById:
    handler: src/functions/handlers.getUserById
    tracing: true
    events:
      - httpApi:
          path: /user/{id}
          method: get
  troubleMaker:          
    handler: src/functions/handlers.troubleMaker
    tracing: true
    events:
      - httpApi:
          path: /whichException/{whichOne}
          method: get
    
resources:
  Resources:
    UsersListTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: UsersListNext
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CustomAlarmLatency:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: 'My custom alarm latency'
        AlarmActions:
          - !Ref InvocationAlarmSNSTopic
        Namespace: 'AWS/Lambda'
        EvaluationPeriods: 3
        MetricName: Duration
        Statistic: Average
        Threshold: 1000
        ComparisonOperator: GreaterThanThreshold
        Period: 60
        TreatMissingData: missing
    CustomAlarmErrors:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmDescription: 'My custom alarm errors'
        AlarmActions:
          - !Ref InvocationAlarmSNSTopic
        Namespace: 'AWS/Lambda'
        EvaluationPeriods: 2
        MetricName: Errors
        Statistic: Sum
        Threshold: 2
        ComparisonOperator: GreaterThanThreshold
        Period: 60
        TreatMissingData: missing
    InvocationAlarmSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        Subscription:
          - Endpoint: niels.mijnster@nn-group.com
            Protocol: email